# Generated by Django 6.0.4 on 2026-09-06 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_servicerequest_tracking_arrived'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianSupportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLVED', 'Solved'), ('ESCALATED', 'Escalated'), ('ABANDONED', 'Abandoned')], default='ACTIVE', max_length=20)),
                ('flow_state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('related_incentive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_sessions', to='core.incentive')),
                ('related_service_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_sessions', to='core.servicerequest')),
                ('related_wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_sessions', to='core.technicianwallettransaction')),
                ('related_withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_sessions', to='core.withdrawalrequest')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_sessions', to='core.technician_signup')),
            ],
            options={
                'db_table': 'TechnicianSupportSession',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianSupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_type', models.CharField(choices=[('SYSTEM', 'System'), ('TECHNICIAN', 'Technician'), ('ADMIN', 'Admin')], max_length=20)),
                ('message', models.TextField()),
                ('options_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technician_support_messages', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.techniciansupportsession')),
            ],
            options={
                'db_table': 'TechnicianSupportMessage',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianSupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=20, unique=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('issue', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('unread_admin_count', models.IntegerField(default=0)),
                ('unread_technician_count', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(auto_now_add=True)),
                ('escalated_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='core.techniciansupportsession')),
            ],
            options={
                'db_table': 'TechnicianSupportTicket',
                'ordering': ['-escalated_at'],
            },
        ),
    ]
